JP_CHUNK_LENGTH_LIMIT = 2000
EN_CHUNK_WORD_LIMIT = 1000

NOTION_BLOCK_REQUEST_LIMIT = 100
NOTION_TEXT_REQUEST_LIMIT = 2000

# USE_LLM_MODEL = "gemini-flash" | "claude-haiku"
USE_LLM_MODEL = "gemini-flash"
IS_ASYNC_REQUEST = True